//
//  File name: FeedbackView.swift
//  Project name: apple-custom-settings-view
//  Workspace name: apple-custom-settings-view
//
//  Created by: nothing-to-add on 19/04/2026
//  Using Swift 6.0
//  Copyright (c) 2023 nothing-to-add
//

import SwiftUI
import MessageUI

// MARK: - FeedbackView

/// A SwiftUI wrapper around `MFMailComposeViewController` for in-app feedback email composition.
///
/// `FeedbackView` is presented as a sheet by `SettingsView` when the user taps a
/// `.feedback` row and the device can send mail. It pre-fills the recipient, subject,
/// and a structured plain-text body generated by ``FeedbackManager/createFeedbackTemplate()``.
///
/// You don't normally instantiate `FeedbackView` directly — use the
/// ``SettingsItem/feedback(appName:email:)`` preset and let `SettingsView` manage presentation.
struct FeedbackView: UIViewControllerRepresentable {
    /// The recipient e-mail address (pre-filled in the "To" field).
    private let recipient: String

    /// The mail subject line, formatted as `"<AppName> - Feedback"`.
    private let subject: String

    /// The pre-filled plain-text message body from ``FeedbackManager/createFeedbackTemplate()``.
    private let messageBody: String
    
    @Environment(\.dismiss) private var dismiss
    
    /// Creates a `FeedbackView` ready to present the mail-compose UI.
    ///
    /// - Parameters:
    ///   - recipient: The e-mail address the feedback will be sent to.
    ///   - appName: The host app's display name — used in the subject line and body greeting.
    ///   - feedbackManager: The ``FeedbackManager`` instance used to generate the mail body.
    init(recipient: String, appName: String, feedbackManager: FeedbackManager) {
        self.recipient = recipient
        self.subject = "\(appName) - Feedback"
        self.messageBody = feedbackManager.createFeedbackTemplate()
    }
    
    /// Creates and configures the `MFMailComposeViewController`.
    func makeUIViewController(context: Context) -> MFMailComposeViewController {
        let composer = MFMailComposeViewController()
        composer.setSubject(subject)
        composer.setToRecipients([recipient])
        composer.setMessageBody(messageBody, isHTML: false)
        composer.mailComposeDelegate = context.coordinator
        return composer
    }
    
    func updateUIViewController(_ uiViewController: MFMailComposeViewController, context: Context) {}
    
    func makeCoordinator() -> Coordinator {
        Coordinator(parent: self)
    }

    // MARK: - Coordinator

    /// Bridges `MFMailComposeViewControllerDelegate` callbacks into SwiftUI.
    class Coordinator: NSObject, MFMailComposeViewControllerDelegate {
        let parent: FeedbackView
        
        init(parent: FeedbackView) {
            self.parent = parent
        }
        
        /// Dismisses the mail-compose controller after the user sends, saves, or cancels.
        func mailComposeController(_ controller: MFMailComposeViewController, didFinishWith result: MFMailComposeResult, error: Error?) {
            controller.dismiss(animated: true)
        }
    }
}
